### ISSUE TITLE
Chemistry Issues links should be Chemistry Working Group

### ISSUE THREAD

**Issue by barronh** [geoschem/geoschem.github.io#16]
### Name and Institution (Required)

Name: Barron Henderson
Institution: US EPA

### Confirm you have reviewed the following documentation

- [x ] [Support guidelines](https://github.com/geoschem/geoschem.github.io/blob/main/SUPPORT.md)
- [ x] [Current and past Github issues](https://github.com/geoschem/geoschem.github.io/GCClassic/issues)

### Description of your issue or question

Several places on geoschem.github.io, the chemistry working group links to a dead page (Chemistry Issues) instead of [Chemistry Working Group](https://wiki.seas.harvard.edu/geos-chem/index.php/Chemistry_Working_Group).

Examples:
* https://geoschem.github.io/working-groups
* https://geoschem.github.io/steering-committee.html
  * for Barron Henderson, Lu Hu, and Jingqiu Mao

It could be the case elsewhere, but those are the ones that I found. Please update to [Chemistry Working Group](https://wiki.seas.harvard.edu/geos-chem/index.php/Chemistry_Working_Group).

**Comment by msulprizio** [comment]
Thanks for pointing out the broken links @barronh. They are now fixed (via 074d657eca4736ab56cf42390eb265865af896c7).

**Comment by barronh** [comment]
You're the best!
