### ISSUE TITLE
Links to presentations from older IGC meetings are broken

### ISSUE THREAD

**Issue by yantosca** [geoschem/geoschem.github.io#23]
### Name and Institution (Required)

Name: Bob Yantosca
Institution: Harvard + GCST

### Confirm you have reviewed the following documentation

- [x] [Support guidelines](https://github.com/geoschem/geoschem.github.io/blob/main/SUPPORT.md)
- [x] [Current and past Github issues](https://github.com/geoschem/geoschem.github.io/GCClassic/issues)

### Description of your issue or question

@ltmurray wrote:

> I was trying to refer to an older GC meeting presentation of Chris Holmes, and noticed that the Github site is still trying to point to non-existent files at Harvard for certain meetings, e.g.,  [The 7th International GEOS-Chem Meeting](https://geoschem.github.io/igc7.html).  In addition, since the move of the documentation to GitHub, I’ve generally found the top Google results for practical/technical questions about GEOS-Chem to lead to the older dead links.

**Comment by yantosca** [comment]
Thanks @ltmurray for bringing that to our attention.  We have been prioritizing the 14.3.0 development over website updates as to try to freeze the 14.3.0 version before the holidays.  We will look at this in the new year.

**Comment by msulprizio** [comment]
This should now be resolved by https://github.com/geoschem/geoschem.github.io/pull/26
